# -*- coding: utf-8 -*-
"""
Created on Wed Jan 28 11:52:36 2026
Versjon 0 av objektklassifisering av bygningskoder fra matrikkelen
Dato for versjon: 26.01.26
@author: KRHE
"""

# Format: "Bygningskode": ("Beskrivelse", "Kategori")
# Kategorier: "sårbar", "bolig", "vei/industri", "ingen beskyttelse", "skjermingsverdig"
# https://www.ssb.no/klass/klassifikasjoner/31
# https://register.geonorge.no/sosi-kodelister/fkb/bygning/5.0/bygningstype

MATRIKKEL_BYGNINGSTYPE = {
    "111": ("Enebolig",  "bolig"),
    "112": ("Enebolig m/hybel/sokkelleil.",  "bolig"),
    "113": ("Våningshus",  "bolig"),
    "121": ("Tomannsbolig",  "bolig"),
    "122": ("Tomannsbolig, horisontaldelt",  "bolig"),
    "123": ("Våninghus tomannsbolig, vertikaldelt",  "bolig"),
    "124": ("Våningshus tomannsbolig, horisontaldelt",  "bolig"),
    "131": ("Rekkehus",  "bolig"),
    "133": ("Kjede/atriumhus",  "bolig"),
    "135": ("Terrassehus",  "bolig"),
    "136": (" Andre småhus med 3 boliger eller flere",  "bolig"),
    "141": ("Stort frittliggende boligbygg på 2 etg",  "bolig"),
    "142": ("Store frittliggende boligbygg på 3 og 4 etg",  "bolig"),
    "143": ("Store frittliggende boligbygg på 5 etg el mer",  "sårbar"),
    "144": ("Store sammenbygde boligbygg på 2 etg",  "bolig"),
    "145": ("Store sammenbygde boligbygg på 3 og 4 etg",  "bolig"),
    "146": ("Store sammenbygde boligbygg på 5 etg el mer",  "sårbar"),
    "151": ("Bo- og servicesenter for eldre, utviklingshemmede, funksjonshemmede mv.",  "sårbar"),
    "152": ("Studenthjem/studentboliger",  "bolig"),
    "159": ("Annen bygning for bofellesskap",  "bolig"),
    "161": ("Hytter, sommerhus og lignende fritidsbygning",  "bolig"),
    "162": ("Helårsboligs som benyttes som fritidsbygning",  "bolig"),
    "163": ("Våninghus som benyttes som fritidsbolig",  "bolig"),
    "171": ("Seterhus, sel, rorbu og lignende",  "vei/industri"),
    "172": ("Skogs- og utmarkskoie, gamme",  "vei/industri"),
    "181": ("Garasje, uthus, anneks til bolig",  "ingen beskyttelse"),
    "182": ("Garasje, uthus, anneks til fritidbolig",  "ingen beskyttelse"),
    "183": ("Naust, båthus, sjøbu",  "ingen beskyttelse"),
    "193": ("Boligbrakker",  "bolig"),
    "199": ("Annen boligbygning",  "bolig"),
    "211": ("Fabrikkbygning",  "vei/industri"),
    "212": ("Verkstedbygning",  "vei/industri"),
    "214": ("Bygning for renseanlegg (bl.a. kloakkpumpestasjon)",  "skjermingsverdig"),
    "216": ("Bygning for vannforsyning (bl.a. pumpestasjon)",  "skjermingsverdig"),
    "219": ("Annen industribygning ",  "vei/industri"),
    "221": ("Kraftstasjon",  "skjermingsverdig"),
    "223": ("Transformatorstasjon",  "skjermingsverdig"),
    "229": ("Annen energiforsyning",  "skjermingsverdig"),
    "231": ("Lagerhall",  "vei/industri"),
    "232": ("Kjøle og fryserlager",  "vei/industri"),
    "233": ("Silobygning",  "skjermingsverdig"),
    "239": ("Annen lagerbygning",  "ingen beskyttelse"),
    "241": ("Hus for dyr/landbruk, lager/silo",  "vei/industri"),
    "243": ("Veksthus",  "vei/industri"),
    "244": ("Driftsbygning fiske/fangst/oppdrett",  "vei/industri"),
    "245": ("Naust, redskapshus for fiske",  "ingen beskyttelse"),
    "248": ("Annen fiskeri- og fangstbygning",  "ingen beskyttelse"),
    "249": ("Annen landbruksbygning",  "ingen beskyttelse"),
    "311": ("Kontor- og   administrasjonsbygning, rådhus.",  "bolig"),
    "312": ("Bankbygning,   posthus",  "bolig"),
    "313": ("Mediabygning",  "bolig"),
    "319": ("Annen kontorbygning",  "bolig"),
    "321": ("Kjøpesenter,   varehus (bygnings som inneholder flere forskjellige butikker)",  "sårbar"),
    "322": ("Butikkbygning",  "bolig"),
    "323": ("Bensinstasjon",  "vei/industri"),
    "329": ("Annen   forretningsbygning",  "bolig"),
    "330": ("Messe og kongressbygning",  "sårbar"),
    "411": ("Ekspedisjonsbygning,   flyterminal, kontrolltårn",  "sårbar"),
    "412": ("Jernbane og   T-banestasjon",  "sårbar"),
    "415": ("Godsterminal",  "vei/industri"),
    "416": ("Postterminal",  "vei/industri"),
    "419": ("Annen ekspedisjons-   og terminalbygning",  "vei/industri"),
    "429": ("Telekommunikasjonsbygning",  "skjermingsverdig"),
    "431": ("Parkeringshus",  "ingen beskyttelse"),
    "439": ("Annen garasje-/hangarbygning",  "ingen beskyttelse"),
    "441": ("Trafikktilsynsbygning",  "vei/industri"),
    "449": ("Annen veg- og   trafikktilsynsbygning",  "vei/industri"),
    "511": ("Hotellbygning",  "sårbar"),
    "512": ("Motellbygning",  "sårbar"),
    "519": ("Annen hotellbygning",  "sårbar"),
    "521": ("Hospits, pensjonat",  "sårbar"),
    "522": ("Vandrer-, feriehjem",  "sårbar"),
    "523": ("Appartement",  "bolig"),
    "524": ("Camping/utleiehytte",  "bolig"),
    "529": ("Annen bygning for overnatting",  "bolig"),
    "531": ("Restaurantbygning, kafebygning",  "bolig"),
    "532": ("Sentralkjøkken, kantinebygning",  "bolig"),
    "533": ("Gatekjøkken, kioskbygning",  "vei/industri"),
    "539": ("Annen restaurantbygning",  "vei/industri"),
    "611": ("Lekepark",  "sårbar"),
    "612": ("Barnehage",  "sårbar"),
    "613": ("Barneskole",  "sårbar"),
    "614": ("Ungdomsskole",  "sårbar"),
    "615": ("Kombinert barne- og ungdomsskole",  "sårbar"),
    "616": ("Videregående skole",  "sårbar"),
    "619": ("Annen skolebygning",  "sårbar"),
    "621": ("Universitet, høgskole m/auditorie, lesesal mv.",  "sårbar"),
    "623": ("Laboratoriebygning",  "sårbar"),
    "629": ("Annen universitet, høgskole og forskningsbygning",  "sårbar"),
    "641": ("Museum, kunstgalleri",  "sårbar"),
    "642": ("Bibliotek, mediatek",  "sårbar"),
    "643": ("Zoologisk og   botanisk hage",  "bolig"),
    "649": ("Annen museums- og biblioteksbygning",  "sårbar"),
    "651": ("Idrettshall",  "sårbar"),
    "652": ("Ishall",  "sårbar"),
    "653": ("Svømmehall",  "sårbar"),
    "654": ("Tribune og   idrettsgarderobe",  "sårbar"),
    "655": ("Helsestudio",  "bolig"),
    "659": ("Annen idrettsbygning",  "bolig"),
    "661": ("Kinobygning. teaterbygning, opera/konserthus",  "sårbar"),
    "662": ("Samfunnshus, grendehus",  "sårbar"),
    "663": ("Diskotek",  "sårbar"),
    "669": ("Annet kulturhus",  "sårbar"),
    "671": ("Kirke, kapell",  "sårbar"),
    "672": ("Bedehus,   menighetshus",  "sårbar"),
    "673": ("Krematorium, gravkapell, bårehus",  "bolig"),
    "674": ("Synage og moske",  "sårbar"),
    "675": ("Kloster",  "sårbar"),
    "679": ("Annen bygninger for religiøse aktiviteter",  "sårbar"),
    "719": ("Sykehus",  "sårbar"),
    "721": ("Sykehjem",  "sårbar"),
    "722": ("Bo- og behandlingssenter",  "sårbar"),
    "723": ("Rehabiliteringsinstitusjon, kurbad",  "sårbar"),
    "729": ("Annet sykehjem",  "sårbar"),
    "731": ("Klinikk, legekontor/-senter/-vakt/dyresykehus",  "sårbar"),
    "732": ("Helse- og sosialsenter, helsestasjon",  "sårbar"),
    "739": ("Annen primærhelsebygning",  "sårbar"),
    "819": ("Fengselsbygning",  "skjermingsverdig"),
    "821": ("Politistasjon",  "sårbar"),
    "822": ("Brannstasjon, ambulansestasjon",  "sårbar"),
    "823": ("Fyrstasjon, losstasjon",  "vei/industri"),
    "824": ("Stasjon for   radarovervåkning av fly- og/eller skipstrafikk",  "skjermingsverdig"),
    "825": ("Tilfluktsrom /   bunker",  "skjermingsverdig"),
    "829": ("Annen   beredskapsbygning",  "skjermingsverdig"),
    "830": ("Monument",  "ingen beskyttelse"),
    "840": ("Offentlig toalett",  "vei/industri"),
    "956": ("Turisthytter",  "bolig"),
    "970": ("Sykehus med   akuttmottak",  "sårbar"),
    "999": ("Ukjent bygningstype",  "sårbar"),
}